# golangci-lint configuration for cloister
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  # Start with defaults and add useful extras
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Examine Go source code for suspicious constructs
    - ineffassign   # Detect ineffective assignments
    - staticcheck   # Static analysis checks
    - unused        # Find unused code
    - gofmt         # Check formatting
    - goimports     # Check import formatting
    - misspell      # Find misspelled words
    - bodyclose     # Check HTTP response body is closed
    - nilerr        # Find nil error returns

linters-settings:
  errcheck:
    # Don't require checking errors for these functions
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

  goimports:
    local-prefixes: github.com/xdg/cloister

  misspell:
    locale: US

issues:
  # Show all issues from a linter
  max-issues-per-linter: 0
  max-same-issues: 0
